sudo: required
services:
  - docker

before_install:
  - docker build -t coregatekit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true coregatekit/react-test npm test 

after_success:
  - docker build -t coregatekit/multi-client ./client
  - docker build -t coregatekit/multi-nginx ./nginx
  - docker build -t coregatekit/multi-server ./server
  - docker build -t coregatekit/multi-worker ./worker

  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take thos image and push them to docker hub
  - docker push coregatekit/multi-client
  - docker push coregatekit/multi-nginx
  - docker push coregatekit/multi-server
  - docker push coregatekit/multi-worker

# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: ap-southeast-1
#   app: multi-docker-service
#   env: MultiDockerService-env
#   bucket_name: elasticbeanstalk-ap-southeast-1-290929644176
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY